# Funding options for this project.
# Uncomment a line and fill in your username/id to enable the Sponsor button.
#
# github: [idanmann10]
# ko_fi: idanmann10
# open_collective: shopdeals
# custom: ['https://shopdeals.sh/support']
